Add form model
ivan1945kozhevnikov/calorie-counter-mvp pull request #4
Opened 2023-05-02 18:22 UTC by ivan1945kozhevnikov

2023-05-03 12:08 UTC, dmitryermolenko requested changes

2023-05-03 12:08 UTC, dmitryermolenko commented on src/js/model/CounterFormModel.js
> +        this.genderValue = null;
Почему null? Здесь должны лежать те значения, которые сейчас в константах лежат

Само поле приватное и без слова value в названии

2023-05-03 12:08 UTC, dmitryermolenko commented on src/js/model/CounterFormModel.js
> +        this.physicalCharacteristicValue = null;
Почему null? Здесь должны лежать те значения, которые сейчас в константах лежат

Само поле приватное и без слова value в названии + название во мн.ч

2023-05-03 12:08 UTC, dmitryermolenko commented on src/js/model/CounterFormModel.js
> +        this.physicalActivityValue = null;
Почему null? Здесь должны лежать те значения, которые сейчас в константах лежат

Само поле приватное и без слова value в названии + название во мн.ч

2023-05-03 12:08 UTC, dmitryermolenko commented on src/js/model/CounterFormModel.js
> +    _findGenderValue() {
Это публичный метод, его нужно дергать, чтобы передать значение в конструктор вью

2023-05-03 12:08 UTC, dmitryermolenko commented on src/js/model/CounterFormModel.js
> +    _findPhysicalCharacteristicsValue() {
Это публичный метод, его нужно дергать, чтобы передать значение в конструктор вью

2023-05-03 12:08 UTC, dmitryermolenko commented on src/js/model/CounterFormModel.js
> +    _findPhysicalActivitiesValue() {
Это публичный метод, его нужно дергать, чтобы передать значение в конструктор вью

2023-05-03 12:08 UTC, dmitryermolenko commented on src/js/model/CounterFormModel.js
> +    _findPhysicalCharacteristicsValue() {
В названии лучше использовать глагол get

2023-05-03 12:08 UTC, dmitryermolenko commented on src/js/model/CounterFormModel.js
> +    _findPhysicalActivitiesValue() {
В названии лучше использовать глагол get

2023-05-03 12:08 UTC, dmitryermolenko commented on src/js/model/CounterFormModel.js
> +        this.genderValue = gender;
Метод не устанавливает значение, а только возвращает

2023-05-03 12:08 UTC, dmitryermolenko commented on src/js/model/CounterFormModel.js
> +        this.physicalCharacteristicValue = physicalCharacteristics;
Метод не устанавливает значение, а только возвращает

2023-05-03 12:08 UTC, dmitryermolenko commented on src/js/model/CounterFormModel.js
> +        this.physicalActivityValue = physicalActivities;
Метод не устанавливает значение, а только возвращает

2023-05-03 12:08 UTC, dmitryermolenko commented on src/js/index.js
> +console.log(formModel);
Убрать

2023-05-03 12:08 UTC, dmitryermolenko commented on src/js/index.js
>  );
Заменить значения констант на вызовы соответствующих методов модели

2023-05-03 12:17 UTC, ivan1945kozhevnikov commented on src/js/model/CounterFormModel.js
> +        this.genderValue = null;
ok

2023-05-03 12:18 UTC, ivan1945kozhevnikov commented on src/js/model/CounterFormModel.js
> +        this.physicalCharacteristicValue = null;
ok

2023-05-03 12:27 UTC, ivan1945kozhevnikov commented on src/js/model/CounterFormModel.js
> +        this.physicalActivityValue = null;
ok

2023-05-03 12:27 UTC, ivan1945kozhevnikov commented on src/js/model/CounterFormModel.js
> +    _findGenderValue() {
ok

2023-05-03 12:27 UTC, ivan1945kozhevnikov commented on src/js/model/CounterFormModel.js
> +    _findPhysicalCharacteristicsValue() {
ok

2023-05-03 12:27 UTC, ivan1945kozhevnikov commented on src/js/model/CounterFormModel.js
> +        this.genderValue = gender;
ok

2023-05-03 12:27 UTC, ivan1945kozhevnikov commented on src/js/model/CounterFormModel.js
> +        this.physicalCharacteristicValue = physicalCharacteristics;
ok

2023-05-03 12:27 UTC, ivan1945kozhevnikov commented on src/js/model/CounterFormModel.js
> +        this.physicalActivityValue = physicalActivities;
ok

2023-05-03 12:27 UTC, ivan1945kozhevnikov commented on src/js/index.js
> +console.log(formModel);
ok

2023-05-03 12:27 UTC, ivan1945kozhevnikov commented on src/js/index.js
>  );
ok

2023-05-03 16:31 UTC, ivan1945kozhevnikov commented on src/js/model/CounterFormModel.js
> +    _findPhysicalActivitiesValue() {
ok

2023-05-03 16:31 UTC, ivan1945kozhevnikov commented on src/js/model/CounterFormModel.js
> +    _findPhysicalCharacteristicsValue() {
ok

2023-05-03 16:31 UTC, ivan1945kozhevnikov commented on src/js/model/CounterFormModel.js
> +    _findPhysicalActivitiesValue() {
ok

2023-05-05 08:12 UTC, dmitryermolenko requested changes
Request changes

2023-05-05 08:12 UTC, dmitryermolenko commented on src/js/model/CounterFormModel.js
> +        this._valueGender = this._gender[0].value;
про слово value я тебе уже писал: это как человеку дать имя Человек
тут все в той или иной степени является значением, и получается масло масленное
this._selectedGender - это более подходящее название, т.к это поле хранит выбранное значение пола + 
значение поля должно быть хардкодом, а не this._gender[0].value

2023-05-05 08:12 UTC, dmitryermolenko commented on src/js/model/CounterFormModel.js
> +    getvalueGender() {
здесь тоже переименовать метод

2023-05-05 08:12 UTC, dmitryermolenko commented on src/js/view/counterFormView.js
> +        valueGender
переименовать

2023-05-05 08:12 UTC, dmitryermolenko commented on src/js/view/counterFormView.js
> +        this.valueGender = valueGender;
переименовать

2023-05-05 08:12 UTC, dmitryermolenko commented on src/js/view/counterFormView.js
> +                 })
дублирование кода, отличается только атрибутом  checked

2023-05-05 08:12 UTC, dmitryermolenko commented on src/js/view/counterFormView.js
> +                        <label for="gender-male"> ${label} </label></li>`;
взять только этот кусок кода и через тернарник сделать проверку, которую ты сейчас делаешь в if, только  для атрибута  checked

2023-05-09 12:45 UTC, dmitryermolenko approved these changes

2023-05-09 12:47 UTC, merged